services:
  api-gateway:
    build: .
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_ISSUER_URI: http://auth-service:9000   # <- clave
      CLIENTES_BASE_URL: http://cliente-service:8080
      PEDIDOS_BASE_URL:  http://pedido-service:8080
      TRACKING_BASE_URL: http://tracking-service:8080
      CORS_ALLOWED_ORIGINS: http://localhost:4200,http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    external: true
