name: proy-unidad

networks:
  appnet:            # red compartida entre microservicios
    name: appnet
  cliente-dbnet:     # redes internas para cada DB
    internal: true
  pedido-dbnet:
    internal: true
  tracking-dbnet:
    internal: true

volumes:
  clientes-data:
  pedidos-data:

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_ISSUER_URI: http://auth-service:9000
      CLIENTES_BASE_URL: http://cliente-service:8080
      PEDIDOS_BASE_URL:  http://pedido-service:8080
      TRACKING_BASE_URL: http://tracking-service:8080
      CORS_ALLOWED_ORIGINS: http://localhost:4200,http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - cliente-service
      - pedido-service
      - tracking-service
    networks:
      - appnet

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_ISSUER: http://auth-service:9000
    ports:
      - "9000:9000"
    networks:
      - appnet

  cliente-service:
    build: ./cliente-service
    container_name: cliente-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://clientes-db:5432/clientes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8080"
    depends_on:
      - clientes-db
    networks:
      - appnet
      - cliente-dbnet

  clientes-db:
    image: postgres:16
    container_name: clientes-db
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - clientes-data:/var/lib/postgresql/data
    networks:
      - cliente-dbnet

  pedido-service:
    build: ./pedido-service
    container_name: pedido-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://pedidos-db:3306/pedidos?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8080"
    depends_on:
      - pedidos-db
    networks:
      - appnet
      - pedido-dbnet

  pedidos-db:
    image: mysql:8.4
    container_name: pedidos-db
    environment:
      MYSQL_DATABASE: pedidos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - pedidos-data:/var/lib/mysql
    networks:
      - pedido-dbnet

  tracking-service:
    build: ./tracking-service
    container_name: tracking-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_REDIS_HOST: tracking-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8083:8080"
    depends_on:
      - tracking-redis
    networks:
      - appnet
      - tracking-dbnet

  tracking-redis:
    image: redis:7.2-alpine
    container_name: tracking-redis
    ports:
      - "6380:6379"
    networks:
      - tracking-dbnet
