spring:
  application:
    name: tracking-service
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: tracking-redis
      port: 6379
      timeout: 2000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://host.docker.internal:9000}
